title: My Jekyll site
author: JEA
email: tk@tk.com
description: > # this means to ignore newlines until "baseurl:"
  A description.

# social links
twitter_username: /nah
github_username:  /abelsj60

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
